### ISSUE TITLE
Complete clone of original code.

### ISSUE THREAD

**Issue by braeden** [gautamkumarjaiswal/magicCloak#1]
https://github.com/mostafiz76/Harry-Potter-s-magical-Cloak-with-opencv

You just ripped off this repo directly without even forking it. It doesn't matter that you added a link at the bottom of your README. You're passing this off as your own work which it is not.

**Comment by gautamkumarjaiswal** [comment]
Hi Braden, I stared the Mostafiz repository when I found his code. However, I didn't fork it because I was not sure that I am going to upload it in my repo and this code is very common. (As per my best knowledge, the repo you suggested to me to fork is taken from [this](https://www.learnopencv.com/invisibility-cloak-using-color-detection-and-segmentation-with-opencv/) tutorial **without** any reference, it is not a new application or technology) . After changing Hue values to identify other colors I found red color perform best. Also, I reduced the range of hue, as well as added 2 lines to exit from the video stream. As my contribution is a few lines, therefore, I didn't modify the date and name of the author in the original script. Also, I added a link of code as a reference and my intention is not to show that it is my original work, as the same work is published in more than 30 webpages including geekforgeek.com to learonpencv tutorials. I mean, this code is quite common (5 lines of code are enough to bring this effect) and all followed almost the same approach by changing variables name. However, as per your suggestion, I forked his repo. I hope, everything is alright now. Thanks for your feedback.
